// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generated from the docs/ folder structure and each file's
  // sidebar_position / _category_.json.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
